name: learn-github-actions
on: [push]

# on:
#   push:
#     branches:
#       - '**'      # matches every branch
#       - '!master' # excludes master

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen4"
